// lib/fonts.js — GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand.
//
// Every typeface that ships inside the extension: family, weight, the file in
// fonts/, and the unicode-range Google Fonts states for that subset. content.js
// turns these into @font-face rules pointing at chrome.runtime.getURL, so the
// interface needs no network and no page's CSP can refuse it.
//
// Regenerate after changing which typesets are `bundled` in lib/languages.js:
//     node scripts/fetch-fonts.mjs

(function (root, factory) {
    const api = factory();
    if (typeof module === 'object' && module.exports) module.exports = api;
    else root.CRFonts = api;
})(typeof self !== 'undefined' ? self : this, function () {
    return {
        FACES: [
        { family: "Inter", weight: "400 800", file: "inter-latin.woff2", range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
        { family: "Inter", weight: "400 800", file: "inter-cyrillic.woff2", range: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
        { family: "Inter", weight: "400 800", file: "inter-greek.woff2", range: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
        { family: "Noto Sans Sinhala", weight: "400 800", file: "noto-sinhala.woff2", range: "U+0964-0965, U+0D81-0DF4, U+1CF2, U+200C-200D, U+25CC, U+111E1-111F4" },
        { family: "Noto Sans Tamil", weight: "400 800", file: "noto-tamil.woff2", range: "U+0964-0965, U+0B82-0BFA, U+200C-200D, U+20B9, U+25CC" },
        { family: "Noto Sans Devanagari", weight: "400 800", file: "noto-devanagari.woff2", range: "U+0900-097F, U+1CD0-1CF9, U+200C-200D, U+20A8, U+20B9, U+20F0, U+25CC, U+A830-A839, U+A8E0-A8FF, U+11B00-11B09" },
        { family: "Noto Sans Arabic", weight: "400 800", file: "noto-arabic.woff2", range: "U+0600-06FF, U+0750-077F, U+0870-088E, U+0890-0891, U+0897-08E1, U+08E3-08FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE70-FE74, U+FE76-FEFC, U+102E0-102FB, U+10E60-10E7E, U+10EC2-10EC4, U+10EFC-10EFF, U+1EE00-1EE03, U+1EE05-1EE1F, U+1EE21-1EE22, U+1EE24, U+1EE27, U+1EE29-1EE32, U+1EE34-1EE37, U+1EE39, U+1EE3B, U+1EE42, U+1EE47, U+1EE49, U+1EE4B, U+1EE4D-1EE4F, U+1EE51-1EE52, U+1EE54, U+1EE57, U+1EE59, U+1EE5B, U+1EE5D, U+1EE5F, U+1EE61-1EE62, U+1EE64, U+1EE67-1EE6A, U+1EE6C-1EE72, U+1EE74-1EE77, U+1EE79-1EE7C, U+1EE7E, U+1EE80-1EE89, U+1EE8B-1EE9B, U+1EEA1-1EEA3, U+1EEA5-1EEA9, U+1EEAB-1EEBB, U+1EEF0-1EEF1" },
        { family: "Noto Sans Armenian", weight: "400 800", file: "noto-armenian.woff2", range: "U+0308, U+0530-058F, U+2010, U+2024, U+25CC, U+FB13-FB17" },
        { family: "Noto Sans Georgian", weight: "400 800", file: "noto-georgian.woff2", range: "U+0589, U+10A0-10FF, U+1C90-1CBA, U+1CBD-1CBF, U+205A, U+2D00-2D2F, U+2E31" },
        { family: "Noto Sans Hebrew", weight: "400 800", file: "noto-hebrew.woff2", range: "U+0307-0308, U+0590-05FF, U+200C-2010, U+20AA, U+25CC, U+FB1D-FB4F" },
        { family: "Noto Sans Thaana", weight: "400 800", file: "noto-thaana.woff2", range: "U+060C, U+061B-061C, U+061F, U+0660-066C, U+0780-07B1, U+200C-200F, U+25CC, U+FDF2, U+FDFD" },
        { family: "Noto Sans Ethiopic", weight: "400 800", file: "noto-ethiopic.woff2", range: "U+030E, U+1200-1399, U+2D80-2DDE, U+AB01-AB2E, U+1E7E0-1E7E6, U+1E7E8-1E7EB, U+1E7ED-1E7EE, U+1E7F0-1E7FE" },
        { family: "Noto Sans Bengali", weight: "400 800", file: "noto-bengali.woff2", range: "U+0951-0952, U+0964-0965, U+0980-09FE, U+1CD0, U+1CD2, U+1CD5-1CD6, U+1CD8, U+1CE1, U+1CEA, U+1CED, U+1CF2, U+1CF5-1CF7, U+200C-200D, U+20B9, U+25CC, U+A8F1" },
        { family: "Noto Sans Gujarati", weight: "400 800", file: "noto-gujarati.woff2", range: "U+0951-0952, U+0964-0965, U+0A80-0AFF, U+200C-200D, U+20B9, U+25CC, U+A830-A839" },
        { family: "Noto Sans Gurmukhi", weight: "400 800", file: "noto-gurmukhi.woff2", range: "U+0951-0952, U+0964-0965, U+0A01-0A76, U+200C-200D, U+20B9, U+25CC, U+262C, U+A830-A839" },
        { family: "Noto Sans Oriya", weight: "400 800", file: "noto-oriya.woff2", range: "U+0951-0952, U+0964-0965, U+0B01-0B77, U+1CDA, U+1CF2, U+200C-200D, U+20B9, U+25CC" },
        { family: "Noto Sans Telugu", weight: "400 800", file: "noto-telugu.woff2", range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC" },
        { family: "Noto Sans Kannada", weight: "400 800", file: "noto-kannada.woff2", range: "U+0951-0952, U+0964-0965, U+0C80-0CF3, U+1CD0, U+1CD2-1CD3, U+1CDA, U+1CF2, U+1CF4, U+200C-200D, U+20B9, U+25CC, U+A830-A835" },
        { family: "Noto Sans Malayalam", weight: "400 800", file: "noto-malayalam.woff2", range: "U+0307, U+0323, U+0951-0952, U+0964-0965, U+0D00-0D7F, U+1CDA, U+1CF2, U+200C-200D, U+20B9, U+25CC, U+A830-A832" },
        { family: "Noto Sans Thai", weight: "400 800", file: "noto-thai.woff2", range: "U+02D7, U+0303, U+0331, U+0E01-0E5B, U+200C-200D, U+25CC" },
        { family: "Noto Sans Lao", weight: "400 800", file: "noto-lao.woff2", range: "U+0E81-0EDF, U+200C-200D, U+25CC" },
        { family: "Noto Sans Khmer", weight: "400 800", file: "noto-khmer.woff2", range: "U+1780-17FF, U+19E0-19FF, U+200C-200D, U+25CC" },
        { family: "Noto Sans Myanmar", weight: "400 800", file: "noto-myanmar.woff2", range: "U+1000-109F, U+200C-200D, U+25CC, U+A92E, U+A9E0-A9FE, U+AA60-AA7F, U+116D0-116E3" },
        { family: "Noto Sans Meetei Mayek", weight: "400 800", file: "noto-meetei.woff2", range: "U+200C-200D, U+25CC, U+AAE0-AAF6, U+ABC0-ABFF" },
        ],
    };
});
